[cred]
PublicKey = "yXb9QMjIaNKsSvHVfyDf92Wjsab3cPw/KxhGVHD4Ds1EMZRCoEdTKs7cOLE="
PrivateKey = "tRY4rBhAobQpYHlfLpc6UsNZZASddkEOivVjfoWhkJLno4XprESwDYbu3hiOpZ/P"

[host]
LoginMode = "Publickey"
ChargeType = "Postpay"
CPU = 8
Memory = 8192
NetCapability = "Ultra"
MachineType = "O"
MinimalCpuPlatform = "Intel/Auto"
NetworkInterface = [
	{
		Bandwidth =   100,
		PayMode =    "Traffic"
		# 可选 cn-sh1: Bgp cn-sh2: Bgp cn-gd: Bgp cn-bj1: Bgp cn-bj2:
		# OperatorName = "Bgp cn-sh2"
	},
]
Disks = [
	{
		IsBoot = "True",
		Size = 20,
		Type =  "CLOUD_RSSD"
	},
]