[cred]
PublicKey = "" 
PrivateKey = ""

[host]
ChargeType = "Postpay"
CPU = 8
Memory = 8192
NetCapability = "Ultra"
MachineType = "O"
# 支持 "Intel/Auto, Amd/Epyc2"
MinimalCpuPlatform = "Intel/Auto"
NetworkInterface = [
	{
		Bandwidth =   100,
		PayMode =    "Traffic"
	},
]
Disks = [
	{
		IsBoot = "True",
		Size = 20,
		Type =  "CLOUD_RSSD"
	},
]